/* Cookie 工具：列出当前活动标签站点的 Cookie，支持三种格式导出与清空 */
const $ = s => document.querySelector(s);
let current = [];

async function activeTab() {
  const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
  return tab;
}

async function load() {
  const tab = await activeTab();
  const rows = $('#rows'), err = $('#err');
  err.textContent = '';
  current = [];
  if (!tab || !/^https?:/i.test(tab.url || '')) {
    $('#host').textContent = '（请先打开一个网页再进本页）';
    rows.innerHTML = ''; return;
  }
  const u = new URL(tab.url);
  $('#host').textContent = u.hostname;
  try {
    current = await chrome.cookies.getAll({ domain: u.hostname });
  } catch (e) { err.textContent = '读取失败：' + e.message; }
  current.sort((a, b) => a.name.localeCompare(b.name));
  rows.innerHTML = current.map(c => {
    const exp = c.session ? '会话' : new Date(c.expirationDate * 1000).toLocaleString();
    const val = (c.value.length > 60 ? c.value.slice(0, 60) + '…' : c.value);
    return `<tr><td>${esc(c.name)}</td><td>${esc(val)}</td><td>${esc(c.domain)}</td><td>${esc(exp)}</td></tr>`;
  }).join('') || '<tr><td colspan="4" class="tip">没有 Cookie</td></tr>';
}

function esc(s) { return String(s).replace(/[&<>"]/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[ch])); }

function headerStr() { return current.map(c => `${c.name}=${c.value}`).join('; '); }
function jsonStr() { return JSON.stringify(Object.fromEntries(current.map(c => [c.name, c.value])), null, 2); }
function netscapeStr() {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by JZX Lite'];
  for (const c of current) {
    const exp = c.session ? 0 : Math.floor(c.expirationDate);
    const flag = c.hostOnly ? 'FALSE' : 'TRUE';
    const domain = c.domain.startsWith('.') ? c.domain : c.domain;
    lines.push([domain, flag, c.path || '/', String(c.secure).toUpperCase(), String(exp), c.name, c.value].join('\t'));
  }
  return lines.join('\n');
}

async function copy(text, label) {
  $('#out').value = text;
  try { await navigator.clipboard.writeText(text); ok(label + ' 已复制到剪贴板'); }
  catch { ok('已生成到下方文本框，请手动复制'); }
}
function ok(msg) { $('#err').style.color = '#18a058'; $('#err').textContent = msg; setTimeout(() => { $('#err').textContent = ''; }, 2500); }

$('#reload').addEventListener('click', load);
$('#copyHeader').addEventListener('click', () => copy(headerStr(), '请求头'));
$('#copyJson').addEventListener('click', () => copy(jsonStr(), 'JSON'));
$('#copyNetscape').addEventListener('click', () => copy(netscapeStr(), 'Netscape'));
$('#delAll').addEventListener('click', async () => {
  if (!current.length) return;
  if (!confirm(`确定清空 ${$('#host').textContent} 的 ${current.length} 条 Cookie？可能需要重新登录。`)) return;
  for (const c of current) {
    const details = { url: `http${c.secure ? 's' : ''}://${(c.domain.startsWith('.') ? c.domain.slice(1) : c.domain)}${c.path || '/'}`, name: c.name };
    try { await chrome.cookies.remove(details); } catch {}
  }
  ok('已清空'); load();
});

load();
